### ISSUE TITLE
`Storms` needs a `loi`... and this is not very convenient

### ISSUE THREAD

**Issue by thomasarsouze** [umr-amap/StormR#57]
### What is your issue?

`loi` argument in `Storms` is mandatory, but this is not very convenient, especialy if we want to retrieve all data from our `StormsDataset`. Also, we cannot specify basins name as `loi`. 
The `Basins` dataframe seems currently unused. It would be good to use it to define basins `loi`.

**Comment by BaptisteDlp** [comment]
In my opinion, `loi` must be mandatory. Each `Storms` object contains in fine a **spatial loi** where the user is looking for storms, meaning that each `Storms`  object corresponds to certain storms at a given location. If one is interested in getting all the storms, it can be done setting a `sf` object with an extent over the whole world for example.

A previous version of `Storms` function allowed the user to set the loi to a specific basin, but I have been told to remove this feature. Nevertheless, I do not think it is necessary because the basin filtering is already performed within the `defDatabase` function. We can still use a flag in the `Storms`function to decide whether or not to get all storms in the database (depending on the basin the filter had been performed)

**Comment by BaptisteDlp** [comment]
Right now, loi remains mandatory in`Storms()`, but the user can choose a basin among `"NA"`, `"SA"`, `"EP"`, `"WP"`, `"SI"`, `"SP"` and `"NI"`
Therefore, I'm closing this issue, but we may upgrade `loi` input in the forthcoming version of the package
