### ISSUE TITLE
[Bug]: temporalBehaviour() does not have verbose = 2 setting

### ISSUE THREAD

**Issue by epingchris** [umr-amap/StormR#63]
### What happened?

If I set verbose = 2 in temporalBehaviour(), it results in the following error message:

Error in checkInputsTempBehaviour(sts, points, product, wind_threshold,  : 
  verbose must be either 0 or 1

Even though the setting 2 is allowed according to the documentation.

### Minimal Complete Verifiable Example

```R
library(StormR)
storm_db = defDatabase(verbose = F)
storm_list = Storms(storm_db, loi = "Vanuatu", seasons = c(2015, 2016), verbose = 0)
wind_df = temporalBehaviour(sts = storm_list,
                            points = data.frame("x" = 166.457510, "y" = -22.254056),
                            wind_threshold = 33,
                            empirical_rmw = T,
                            verbose = 2) #shows error

wind_df = temporalBehaviour(sts = storm_list,
                            points = data.frame("x" = 166.457510, "y" = -22.254056),
                            wind_threshold = 33,
                            empirical_rmw = T,
                            verbose = 1) #no error
```

### Propose a solution

Add the verbose = 2 setting

### Environment

<details>

‘0.1.0’

</details>

**Comment by thomasarsouze** [comment]
Hi @epingchris, and thanks for submitting this issue.

This should be fixed with commit 8be3db8f38c32d87bc992850e5a7941c1c23b056. `verbose = 2` has been added and default behaviour is now `verbose = 1`.

Please note that at the same time, while we're on the process to submit the package to CRAN in an official release, we did some minor renaming of some functions and arguments. Your code above now has to be written:
``` R
library(StormR)
storm_db = defDatabase(verbose = 0)
storm_list = defStormsList(storm_db, loi = "Vanuatu", seasons = c(2015, 2016), verbose = 0)
wind_df = temporalBehaviour(sts = storm_list,
                            points = data.frame("x" = 166.457510, "y" = -22.254056),
                            windThreshold = 33,
                            empiricalRMW = T,
                            verbose = 2)
``` 

Please close the issue if this seems ok to you.
